#!/usr/bin/env ruby

require 'fileutils'
require 'json'
require 'net/http'
require 'nokogiri'
require 'uri'

FileUtils.mkdir_p(ENV['alfred_workflow_cache']) unless Dir.exist?(ENV['alfred_workflow_cache'])
troubleshooting_file = ENV['alfred_workflow_cache'] + '/troubleshooting.json'

alfred_base_url = 'https://www.alfredapp.com'
page = Nokogiri::HTML(Net::HTTP.get(URI.parse(alfred_base_url + '/help/troubleshooting/'))).at('article#helparticle')

script_filter_items = []

page.css('h2').each_with_index do |header, index|
  section_title = header.text
  section_items = page.css('ul')[index].css('li')

  section_items.each do |item|
    item_url = alfred_base_url + item.at('a').attr('href')
    item_title = Nokogiri::HTML(Net::HTTP.get(URI.parse(item_url))).at('h1').text

    script_filter_items.push(title: item_title, subtitle: section_title, match: item_title, arg: item_title + ',' + item_url, quicklookurl: item_url)
  end
end

File.write(troubleshooting_file, { items: script_filter_items }.to_json)
