#!/bin/bash

readonly valid_resources=('cpulimit' 'exiftool' 'ffmpeg' 'mediainfo' 'trash' 'youtubedl') # Keep in sync with resource functions
readonly shared_resources_id='com.vitorgalvao.alfred._sharedresources'
[[ -z "${alfred_workflow_data}" ]] && alfred_workflow_data="$(mktemp -d)/Workflow Data/fake_workflow" # To prevent commands reliant on this variable from breaking when testing outside a Workflow
readonly shared_resources_dir="$(dirname "${alfred_workflow_data}")/${shared_resources_id}"
readonly shared_resources_bin="${shared_resources_dir}/bin"
readonly PATH=/usr/local/bin:"${shared_resources_bin}":"${PATH}"

function wrong_usage {
  echo "
    Could not recognise argument. It needs to be one or more of:
      $(printf "\n  %s" "${valid_resources[@]}")
  " | sed -E 's/^ {4}//' >&2

  exit 1
}

function curl_error {
  echo 'Could not download resource.' >&2
  exit 1
}

function ensure_resources_dir {
  [[ -d "${shared_resources_bin}" ]] || mkdir -p "${shared_resources_bin}"
}

function mount_dmg {
  local dmg_path plist dicts mount_point

  readonly dmg_path="${1}"
  readonly plist="$(mktemp)" # We need to make the plist into a file so PlistBuddy will read it

  hdiutil mount -plist -nobrowse -readonly -mountrandom /tmp "${dmg_path}" > "${plist}"

  readonly dicts="$(/usr/libexec/PlistBuddy -c 'print system-entities' "${plist}" | grep --count 'Dict')"
  for i in $(seq 0 "$(bc <<< "${dicts} - 1")") ; do
    mount_point="$(/usr/libexec/PlistBuddy -c "print system-entities:${i}:mount-point" "${plist}" 2>&1)"
    if grep --quiet --invert-match 'Does Not Exist' <<< "${mount_point}"; then
      break
    fi
  done

  echo -n "${mount_point}"
}

function unmount_dmg {
  hdiutil unmount "${1}" > /dev/null
}

# Resource functions
function cpulimit_getter {
  local cpulimit_path
  cpulimit_path="$(command -v 'cpulimit')"

  if [[ -z "${cpulimit_path}" ]]; then
    local tar_extract cpulimit_version

    cpulimit_path="${shared_resources_bin}/cpulimit"
    readonly cpulimit_version='0.2'
    readonly tar_extract="$(mktemp -d)"

    ensure_resources_dir

    if curl --silent "https://homebrew.bintray.com/bottles/cpulimit-${cpulimit_version}.sierra.bottle.tar.gz" | tar xC "${tar_extract}"; then
      mv "${tar_extract}/cpulimit/${cpulimit_version}/bin/cpulimit" "${cpulimit_path}"
      chmod +x "${cpulimit_path}"
    else
      curl_error
    fi
  fi
}

function exiftool_getter {
  local exiftool_path
  exiftool_path="$(command -v 'exiftool')"

  function get_exiftool {
    local tar_extract lib_dir latest_tag

    exiftool_path="${shared_resources_bin}/exiftool"
    readonly tar_extract="$(mktemp -d)"
    readonly lib_dir="${shared_resources_dir}/exiftool"
    readonly latest_tag="$(curl --silent 'https://api.github.com/repos/exiftool/exiftool/tags' | grep 'tarball_url' | head -1 | sed -E 's/.*: "(.*)".*/\1/')"

    ensure_resources_dir

    if curl --location --silent "${latest_tag}" | tar xC "${tar_extract}"; then
      mv "${tar_extract}/"* "${lib_dir}"
      ln -s "${lib_dir}/exiftool" "${exiftool_path}"
    else
      curl_error
    fi
  }

  if [[ -n "${exiftool_path}" ]]; then
    [[ "${exiftool_path}" == *"${shared_resources_id}"* ]] && [[ $(find "${exiftool_path}" -mtime +90) ]] && get_exiftool
  else
    ensure_resources_dir
    get_exiftool
  fi
}

function ffmpeg_getter {
  local ffmpeg_path
  ffmpeg_path="$(command -v 'ffmpeg')"

  function get_ffmpeg {
    local download_page file_name dmg dmg_mount_point

    ffmpeg_path="${shared_resources_bin}/ffmpeg"
    readonly download_page='https://evermeet.cx/pub/ffmpeg/'
    readonly file_name="$(curl --silent "${download_page}" | grep '.dmg' | grep --invert-match '.sig' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
    readonly dmg="$(mktemp)"

    if curl --silent --output "${dmg}" "${download_page}${file_name}"; then
      readonly dmg_mount_point="$(mount_dmg "${dmg}")"
      cp "${dmg_mount_point}/ffmpeg" "${ffmpeg_path}"
      unmount_dmg "${dmg_mount_point}"
    else
      curl_error
    fi
  }

  if [[ -n "${ffmpeg_path}" ]]; then
    [[ "${ffmpeg_path}" == *"${shared_resources_id}"* ]] && [[ $(find "${ffmpeg_path}" -mtime +90) ]] && get_ffmpeg
  else
    ensure_resources_dir
    get_ffmpeg
  fi
}

function mediainfo_getter {
  local mediainfo_path
  mediainfo_path="$(command -v 'mediainfo')"

  function get_mediainfo {
    local file_name dmg pkg_extract dmg_mount_point

    mediainfo_path="${shared_resources_bin}/mediainfo"
    readonly file_name="$(curl --silent 'https://mediaarea.net/en/MediaInfo/Download/Mac_OS' | grep 'CLI.*.dmg' | head -1 | sed -E 's/.*<a href="(.*)".*/\1/')"
    readonly dmg="$(mktemp)"
    readonly pkg_extract="$(mktemp -d)"

    if curl --silent --output "${dmg}" "https:${file_name}"; then
      readonly dmg_mount_point="$(mount_dmg "${dmg}")"
      cd "${pkg_extract}" || exit 1
      xar -xf "${dmg_mount_point}/mediainfo.pkg"
      gunzip --decompress --stdout 'Payload' | cpio -i 2> /dev/null
      cp './usr/local/bin/mediainfo' "${mediainfo_path}"
      unmount_dmg "${dmg_mount_point}"
      cd - > /dev/null || exit 1
    else
      curl_error
    fi
  }

  if [[ -n "${mediainfo_path}" ]]; then
    [[ "${mediainfo_path}" == *"${shared_resources_id}"* ]] && [[ $(find "${mediainfo_path}" -mtime +90) ]] && get_mediainfo
  else
    ensure_resources_dir
    get_mediainfo
  fi
}

function trash_getter {
  local trash_path
  trash_path="$(command -v 'trash')"

  if [[ -z "${trash_path}" ]]; then
    local tar_extract trash_version

    trash_path="${shared_resources_bin}/trash"
    readonly trash_version='0.9.2'
    readonly tar_extract="$(mktemp -d)"

    ensure_resources_dir

    if curl --silent "https://homebrew.bintray.com/bottles/trash-${trash_version}.sierra.bottle.tar.gz" | tar xC "${tar_extract}"; then
      mv "${tar_extract}/trash/${trash_version}/bin/trash" "${trash_path}"
      chmod +x "${trash_path}"
    else
      curl_error
    fi
  fi
}

function youtubedl_getter {
  local youtubedl_path
  youtubedl_path="$(command -v 'youtube-dl')"

  if [[ -n "${youtubedl_path}" ]]; then
    [[ "${youtubedl_path}" == *"${shared_resources_id}"* ]] && [[ $(find "${youtubedl_path}" -mtime +15) ]] && "${youtubedl_path}" --update --quiet
  else
    ensure_resources_dir
    youtubedl_path="${shared_resources_bin}/youtube-dl"
    if curl --silent --location 'https://yt-dl.org/downloads/latest/youtube-dl' --output "${youtubedl_path}"; then
      chmod +x "${youtubedl_path}"
    else
      curl_error
    fi
  fi
}

resources_to_use=(${@})

# Check if arguments are valid
for rtu_index in "${!resources_to_use[@]}"; do
  for vr_index in "${!valid_resources[@]}"; do
    [[ "${resources_to_use[${rtu_index}]}" == "${valid_resources[${vr_index}]}" ]] && resource_is_valid='true' && break
  done
  [[ -n "${resource_is_valid}" ]] || wrong_usage
  unset resource_is_valid
done

for resource in "${resources_to_use[@]}"; do
  "${resource}_getter" # Run the function to get the tool. '_getter' is required as otherwise the function will detect itself when running 'command'
done

echo -n "${PATH}"
