#!/usr/bin/env ruby

require 'json'
require 'open-uri'
require 'pathname'

# Helpers
def get_env(variable:, default:, as_bool: false, as_pathname: false, match_list: [])
  # If boolean, return early
  if as_bool
    case variable
    when true, 'true', 'yes', 1, '1' then return true
    when false, 'false', 'no', 0, '0', nil, '' then return false
    else raise ArgumentError, "Invalid value: #{variable.inspect}"
    end
  end

  # Extract string
  var_as_string = lambda {
    return default if variable.nil? || variable.empty?
    return variable if match_list.empty? || match_list.include?(variable)

    default
  }.call

  # If pathname, make it now
  return Pathname.new(var_as_string).expand_path if as_pathname

  var_as_string
end

# Constants
Ignored_layouts = %w[art_series double_faced_token scheme token vanguard]
Multi_faced_layout = %w[modal_dfc transform]
Rarity_order = %w[mythic rare uncommon common bonus special]

Sort_by_rarity = get_env(
  variable: ENV['mtg_sort_by_rarity'],
  default: false,
  as_bool: true
)

Cards_json = Pathname.new(ENV['mtg_cards_json'])
Pathname.new(ENV['alfred_workflow_cache']).mkpath

All_cards_info = lambda {
  data_url = JSON.parse(URI('https://api.scryfall.com/bulk-data/oracle-cards').read)['download_uri']
  data = JSON.parse(URI(data_url).read)

  Sort_by_rarity ? data.sort_by { |card_info| Rarity_order.index(card_info['rarity']) } : data
}.call

script_filter_items = []

All_cards_info.each do |card_info|
  next if Ignored_layouts.any? { |layout| card_info['layout'] == layout }

  if Multi_faced_layout.any? { |layout| card_info['layout'] == layout } # If card is doube-faced,
    card = card_info['card_faces'][0] # use info of first face,
    card['rarity'] = card_info['rarity'] # but rarity is of the whole card, not a face
    card['scryfall_uri'] = card_info['scryfall_uri']
  else
    card = card_info
  end

  list =
    if card['mana_cost'].empty? && card['type_line'] =~ /.*Land.*/
      'Lands'
    elsif card['colors'].empty?
      'Colorless'
    elsif card['colors'].length > 1
      'Multi'
    elsif card['colors'].first == 'W'
      'White'
    elsif card['colors'].first == 'U'
      'Blue'
    elsif card['colors'].first == 'B'
      'Black'
    elsif card['colors'].first == 'R'
      'Red'
    elsif card['colors'].first == 'G'
      'Green'
    end

  pt = card['power'].nil? ? '' : " 𐄁 #{card['power']}/#{card['toughness']}"
  rulings = card['oracle_text'].nil? || card['oracle_text'].empty? ? '' : " 𐄁 #{card['oracle_text'].gsub("\n", '. ')}"
  image_size = get_env(
    variable: ENV['mtg_image_size'],
    default: 'png',
    match_list: %w[png large normal small]
  )
  image = card['image_uris'][image_size]

  script_filter_items.push(
    title: card['name'],
    autocomplete: card['name'],
    subtitle: "#{card['mana_cost']} (#{card['cmc'].to_i}) 𐄁 #{card['type_line']}#{pt} 𐄁 #{card['rarity']}#{rulings}",
    quicklookurl: image,
    icon: { path: 'mtg_symbols/' + list + '.png' },
    arg: card['name'] + '|' + card['scryfall_uri'].sub('?utm_source=api', '')
  )
end

Cards_json.write({ items: script_filter_items }.to_json)
