#!/usr/bin/env ruby

require 'cgi'
require 'json'
require 'open-uri'

query = ARGV[0]
api_query = 'https://api.scryfall.com/cards/search?include_multilingual=true&q=' + CGI.escape(query)

begin
  matching_cards = JSON.parse(URI.parse(api_query).read)
rescue OpenURI::HTTPError
  puts({ items: [{ title: "No cards found matching “#{query}”", valid: false }]}.to_json)
end

script_filter_items = []

matching_cards['data'].each do |card|
  pt = card['power'].nil? ? '' : " 𐄁 #{card['power'].to_s}/#{card['toughness'].to_s}"
  rulings = card['oracle_text'].nil? ? '' : " 𐄁 #{card['oracle_text'].gsub("\n", '. ')}"
  image = card['layout'] =~ /(double_faced_token|transform)/ ? card['card_faces'][0]['image_uris']['png'] : card['image_uris']['png']

  script_filter_items.push(
    title: card['name'],
    autocomplete: card['name'],
    subtitle: "#{card['mana_cost']} (#{card['cmc'].to_i}) 𐄁 #{card['type_line']}#{pt} 𐄁 #{card['rarity']}#{rulings}",
    quicklookurl: image,
    arg: card['scryfall_uri'].sub('?utm_source=api', '')
  )
end

puts({ items: script_filter_items }.to_json)
