#!/usr/bin/ruby

require 'cgi'
require 'open3'
require 'pathname'

ENV['PATH'] = Open3.capture2(Pathname.pwd.join('_sharedresources').to_path, 'multimarkdown').first

class String
  def bbcode_sub(html_tag, bbcode_tag)
    gsub("<#{html_tag}>", "[#{bbcode_tag}]").gsub("</#{html_tag}>", "[/#{bbcode_tag}]")
  end
end

# An empty line is added to the beginning of STDIN so text starting with a word and a colon won't be considered metadata
# https://web.archive.org/web/20210804225002/https://fletcher.github.io/MultiMarkdown-5/syntax.html
print CGI.unescapeHTML(Open3.capture2('multimarkdown', '--', stdin_data: "\n#{ARGV[0]}").first).
  gsub('<p>', '').gsub('</p>', "\n").
  bbcode_sub('strong', 'b').
  bbcode_sub('em', 'i').
  bbcode_sub('strikethrough', 's').
  bbcode_sub('underline', 'u').
  gsub(%r{<a href="(.*?)">}, '[url="\1"]').gsub('</a>', '[/url]').
  gsub('<ol>', '[list=1]').gsub('</ol>', '[/list]').
  gsub(%r{<img.*?src=['"](.+?)['"].*?>}, '[img]\1[/img]').
  gsub(%r{</?figure>}, '').gsub(%r{</?figcaption>}, '').
  bbcode_sub('ul', 'list').
  bbcode_sub('li', '*').
  bbcode_sub('blockquote', 'quote').
  gsub(%r{<pre><code.*?>}, '[code]').gsub('</code></pre>', '[/code]').
  gsub('<code>', '[background=#eee][font=courier,monospace]').gsub('</code>', '[/font][/background]').
  gsub(%r{<h1.*?>}, "\n\n[b][size=7]").gsub('</h1>', '[/size][/b]').
  gsub(%r{<h2.*?>}, "\n\n[b][size=6]").gsub('</h2>', '[/size][/b]').
  gsub(%r{<h3.*?>}, "\n\n[b][size=5]").gsub('</h3>', '[/size][/b]').
  gsub(%r{<h4.*?>}, "\n\n[b][size=4]").gsub('</h4>', '[/size][/b]').
  bbcode_sub('sup', 'sup').
  bbcode_sub('sub', 'sub').
  gsub('<hr />', '[hr]').
  gsub(%r{\n{3}\[list(=1)?\]$}, '[list\1]'). # Adjustments to list outward spacing in IPBoard
  gsub(%r{\[/list\]\n{2}}, '[/list]').
  gsub(%r{^$}, "\n"). # Bypass empty line collapsing done by IPBoard
  strip
