#!/usr/bin/ruby

require_relative "#{__dir__}/ensure_redcarpet.rb"

markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, strikethrough: true, superscript: true, fenced_code_blocks: true, autolink: true, footnotes: true, highlight: true, tables: true)

print markdown.render(ARGV[0])
