#!/usr/bin/ruby

require_relative "#{__dir__}/ensure_redcarpet.rb"

class CustomRender < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end
def rouge_markdown(text)
  github_styles = Rouge::Themes::Github.render(scope: '.highlight')
  rich_text_style = "
  <style>
  #{github_styles}
  </style>
  "
  render_options = {
      hard_wrap: true
  }
  renderer = CustomRender.new(render_options)
  extensions = {
    autolink: true,
    fenced_code_blocks: true,
    strikethrough: true,
    superscript: true,
    highlight: true,
    footnotes: true,
    tables: true
  }
  markdown = Redcarpet::Markdown.new(renderer, extensions)

  text =
  rich_text_style +
  markdown
  .render(ARGV[0])
end
text = rouge_markdown(ARGV[0])
print text
