#!/usr/bin/ruby

require_relative "#{__dir__}/ensure_redcarpet.rb"
require 'shellwords'

rich_text_style = '
  <style>
    body { font-family: sans-serif; font-size: 14px; }
    code { background-color: #eee; font-family: courier, monospace; }
    p    { margin: 0; }
  </style>
'

markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, strikethrough: true, superscript: true)

text = markdown.render(ARGV[0])
text = text.gsub(/<img[^>]*>/, '') # Strip images
text = text.gsub('</p>', '</p><br>') # Enforce line breaks after paragraphs
text = rich_text_style + text

system("textutil -inputencoding utf8 -convert rtf -stdin -stdout -format html <<< #{text.shellescape} | pbcopy")
