#!/usr/bin/ruby
# frozen_string_literal: true

require 'open3'
require 'shellwords'
require_relative "#{Dir.pwd}/multimarkdown_bin_arch.rb"

Rich_text_style = '
  <style>
    body { font-family: sans-serif; font-size: 14; }
    code { font-family: monospace; }
    p    { margin: 0; }
  </style>
'

# Need to escape path for shell, otherwise paths with spaces in it won't work
multimarkdown_bin_path = Shellwords.escape(ENV['multimarkdown_bin'])

Html = "
  #{Rich_text_style}
  #{Open3.capture2(multimarkdown_bin_path, stdin_data: ARGV[0]).first}
".
  gsub(/<img[^>]*>/, ''). # Strip images
  gsub('</p>', '</p><br>') # Enforce line breaks after paragraphs

Rtf_text = Open3.capture2(
  'textutil', '-inputencoding', 'utf8', '-convert', 'rtf',
  '-stdin', '-stdout', '-format', 'html',
  stdin_data: Html
).first

rtf_text_lines = Rtf_text.split("\n")
rtf_text_lines.slice!(3..4)

print rtf_text_lines.join("\n")
