#!/bin/bash

readonly url_list="${alfred_workflow_cache}/urls.txt"

function notification {
  /bin/zsh ./Notificator.app/Contents/Resources/Scripts/notificator --message "${1}" --title "${alfred_workflow_name}"
}

function failure {
  notification "${1}" 'Funk'
  exit 1
}

function success {
  notification 'Link copied to clipboard' 'Ping'
}

function prepend {
  if [[ -z "${1}" ]] || [[ ! -f "${2}" ]]; then
    echo 'usage: prepend <line_to_prepend> <file_to_prepend_to>'
    return 1
  else
    local -r line_to_prepend="${1}"
    local -r file_to_prepend_to="${2}"
    local -r tmp_prepend_file="$(mktemp -t prepend)"

    echo "${line_to_prepend}" | cat - "${file_to_prepend_to}" > "${tmp_prepend_file}"
    mv "${tmp_prepend_file}" "${file_to_prepend_to}"
  fi
}

function take_screenshot {
  local -r screenshot_file="$(mktemp).png"

  screencapture -i "${screenshot_file}"

  [[ -s "${screenshot_file}" ]] && upload_file "${screenshot_file}" || failure 'Did not take screenshot'
}

function register_links {
  local -r screenshot_url="${1}"
  local -r screenshot_del="${2}"

  [[ -d "${alfred_workflow_cache}" ]] || mkdir -p "${alfred_workflow_cache}"
  [[ -f "${url_list}" ]] || touch "${url_list}"

  prepend "${screenshot_url}|${screenshot_del}" "${url_list}"
}

function upload_file {
  local -r screenshot_file="${1}"
  local -r upload_response="$(./imgur "${screenshot_file}" 2>&1)" # This will already copy the URL to the clipboard

  [[ "${upload_response}" == 'Upload failed' ]] && failure 'Upload failed'
  success

  local -r screenshot_url="$(head -1 <<< "${upload_response}")"
  local -r screenshot_del="$(tail -1 <<< "${upload_response}" | sed 's/Delete page: //')"

  register_links "${screenshot_url}" "${screenshot_del}"
}

function clipboard_to_image {
  local -r output="${1}"

  osascript -e "
    try
      set imageData to the clipboard as {«class PNGf»}
    on error
      tell me to error \"Clipboard data does not seem to be an image\"
    end try

    set filePath to \"${output}\"

    set imageFile to open for access filePath with write permission
    write imageData to imageFile
    close access imageFile
  "
}
