#!/bin/bash

readonly url_list="${alfred_workflow_cache}/urls.txt"

function notification {
  ./Notificator.app/Contents/Resources/Scripts/notificator --message "${1}" --title "${alfred_workflow_name}"
}

function failure {
  local message="${1}"

  afplay /System/Library/Sounds/Funk.aiff &
  notification "${message}"
  exit 1
}

function success {
  afplay /System/Library/Sounds/Ping.aiff &
  notification 'Link copied to clipboard'
}

function prepend {
  local line_to_prepend file_to_prepend_to tmp_prepend_file

  if [[ -z "${1}" ]] || [[ ! -f "${2}" ]]; then
    echo 'usage: prepend <line_to_prepend> <file_to_prepend_to>'
    return 1
  else
    line_to_prepend="${1}"
    file_to_prepend_to="${2}"
    tmp_prepend_file="$(mktemp -t prepend)"

    echo "${line_to_prepend}" | cat - "${file_to_prepend_to}" > "${tmp_prepend_file}"
    mv "${tmp_prepend_file}" "${file_to_prepend_to}"
  fi
}

function take_screenshot {
  local screenshot_file="$(mktemp).png"

  screencapture -i "${screenshot_file}"

  [[ -s "${screenshot_file}" ]] && upload_file "${screenshot_file}" || failure 'Did not take screenshot'
}

function register_links {
  local screenshot_url="${1}"
  local screenshot_del="${2}"

  [[ -d "${alfred_workflow_cache}" ]] || mkdir -p "${alfred_workflow_cache}"
  [[ -f "${url_list}" ]] || touch "${url_list}"

  prepend "${screenshot_url}|${screenshot_del}" "${url_list}"
}

function upload_file {
  local screenshot_file="${1}"
  local upload_response="$(./imgur "${screenshot_file}" 2>&1)" # This will already copy the URL to the clipboard

  [[ "${upload_response}" == 'Upload failed' ]] && failure 'Upload failed'
  success

  local screenshot_url="$(head -1 <<< "${upload_response}")"
  local screenshot_del="$(tail -1 <<< "${upload_response}" | sed 's/Delete page: //')"

  register_links "${screenshot_url}" "${screenshot_del}"
}
