#!/bin/bash

set -e # Abort on any failure.

imgur_uploader_exec='./imgur'
resample_dpi_exec='./_licensed/resample-dpi/resample-dpi'

tmp_name="$(mktemp -t 'webscreenshot')"
url_list="${alfred_workflow_cache}/urls.txt"

function notification {
  ./Notificator.app/Contents/Resources/Scripts/notificator --message "${1}" --title "${alfred_workflow_name}"
}

function failure {
  afplay /System/Library/Sounds/Funk.aiff &
  notification 'Screenshot not uploaded.'
  exit 1
}

function success {
  afplay /System/Library/Sounds/Ping.aiff &
  notification 'Link copied to clipboard.'
}

function prepend {
  local line_to_prepend file_to_prepend_to tmp_prepend_file

  if [[ -z "${1}" ]] || [[ ! -f "${2}" ]]; then
    echo 'usage: prepend <line_to_prepend> <file_to_prepend_to>'
    return 1
  else
    line_to_prepend="${1}"
    file_to_prepend_to="${2}"
    tmp_prepend_file="$(mktemp -t prepend)"

    echo "${line_to_prepend}" | cat - "${file_to_prepend_to}" > "${tmp_prepend_file}"
    mv "${tmp_prepend_file}" "${file_to_prepend_to}"
  fi
}

function resample_dpi {
  local screenshot_file="${1}"
  bash "${resample_dpi_exec}" "${screenshot_file}" &>/dev/null

  echo "${screenshot_file}"
}

function take_screenshot {
  local screenshot_file="${tmp_name}.png"
  if screencapture -i "${screenshot_file}"; then
    echo "${screenshot_file}"
  else
    failure
  fi
}

function copy_image {
  local file_name="${1}"
  local file_extension="$([[ "${file_name}" = *.* ]] && echo ".${file_name##*.}" || echo '')"
  local screenshot_file="${tmp_name}.${file_extension}"
  cp "${file_name}" "${screenshot_file}"

  echo "${screenshot_file}"
}

function register_links {
  local screenshot_url="${1}"
  local screenshot_del="${2}"

  [[ -d "${alfred_workflow_cache}" ]] || mkdir -p "${alfred_workflow_cache}"
  [[ -f "${url_list}" ]] || touch "${url_list}"

  prepend "${screenshot_url}|${screenshot_del}" "${url_list}"
}

function upload_file {
  local screenshot_file="${1}"
  local upload_response="$(bash "${imgur_uploader_exec}" "${screenshot_file}" 2>&1)" # This will already copy the URL to the clipboard

  [[ "${upload_response}" == 'Upload failed' ]] && failure
  success

  local screenshot_url="$(head -1 <<< "${upload_response}")"
  local screenshot_del="$(tail -1 <<< "${upload_response}" | sed 's/Delete page: //')"

  register_links "${screenshot_url}" "${screenshot_del}"
}

if [[ "${1}" == 'take_screenshot' ]]; then
  screenshot_file=$(take_screenshot)
  shift
elif [[ "${1}" == 'upload_image' ]]; then
  screenshot_file="$(copy_image "${2}")"
  shift 2
fi

if [[ "${1}" == 'resample' ]]; then
  screenshot_file="$(resample_dpi "${screenshot_file}")"
fi

upload_file "${screenshot_file}"
