#!/bin/bash

function notification {
  ./Notificator.app/Contents/Resources/Scripts/notificator --message "${1}" --title "${alfred_workflow_name}"
}

if [[ "${1}" == 'restart_download_true' ]]; then
  notification 'Restarting download at bottom of queue'
  currentquery=$(< '/tmp/downvidcurrentquery')

  osascript -e "tell application id \"com.runningwithcrayons.Alfred\" to run trigger \"new\" in workflow \"com.vitorgalvao.alfred.downvid\" with argument \"${currentquery}\""
else
  notification 'Download aborted'
  rm '/tmp/downvidprogress'
fi

# Kill parent to prevent notification showing success and child to stop download
parent_process="$(pgrep -f 'downvid')"
child_process="$(pgrep -P "${parent_process}")"
kill "${parent_process}" "${child_process}"
