#!/bin/bash

# Settings
notification() {
	./_licensed/terminal-notifier/terminal-notifier.app/Contents/MacOS/terminal-notifier -title "PinAdd" -message "${1}"
}
source ./workflowHandler.sh

token="$(getPref token 1)"
url="$(getPref url 0 titleandurl)"
title="$(getPref title 0 titleandurl)"

# Actions for configuring account, picking tags and description, and setting private bookmark
tags="$@"

if [[ "${tags}" == *"// "* ]]; then
	description=$(awk -F '// ' '{print $2}' <(echo "${tags}"))
	tags=$(awk -F '// ' '{print $1}' <(echo "${tags}"))
fi

if [[ "${tags}" == "{{configureYourAccount}}"* ]]; then
	token=$(cut -d " " -f2 <(echo "${tags}"))
	browser=$(cut -d " " -f3 <(echo "${tags}"))
	setPref token "${token}" 1
	setPref browser "${browser}" 1
	notificator "Account configured"
	exit 0
fi

if [[ "${tags}" == "{{setAsPrivate}}"* ]]; then
	tags="$(echo ${tags} | sed -E 's/{{setAsPrivate}} ?//')"
	private='&shared=no'
else
	private='&shared=yes'
fi

if [[ "${tags}" == "."* ]]; then
	tags="$(echo ${tags} | sed 's/^\.//')"
	toread='&toread=yes'
fi

# Tags and description, url encoded
tags='&tags='$(echo "${tags}" | perl -MURI::Escape -wlne 'print uri_escape ($_)')
description='&extended='$(echo "${description}" | perl -MURI::Escape -wlne 'print uri_escape ($_)')

# Add the bookmark
result=$(curl --silent "https://api.pinboard.in/v1/posts/add?url=${url}&description=${title}&auth_token=${token}${tags}${description}${private}${toread}")

# Warn if there was an error adding the bookmark
result=$(echo "${result}" | sed '1d;3d' | sed 's/.*"\(.*\)".*/\1/')

if [[ ${result} != 'done' ]]; then
	notification "There was a problem adding the bookmark"

	# Add a file on the desktop, with the command to try again
	retry="${HOME}/Desktop/PinAddRetry.command"

	if [[ ! -f "${retry}" ]]; then
		echo '#!/bin/bash' >> "${retry}"
		echo '# Run this script to try again to add the bookmarks (you will have to manually check if it worked)' >> "${retry}"
		chmod +x "${retry}"
	fi
	echo "curl --silent \"https://api.pinboard.in/v1/posts/add?url=${url}&description=${title}&auth_token=${token}${tags}${description}${private}${toread}\"" >> "${retry}"
fi

exit 0
