#!/bin/bash

export NOTIFICATOR_MESSAGE=''
export NOTIFICATOR_TITLE=''
export NOTIFICATOR_SUBTITLE=''
export NOTIFICATOR_SOUND=''

readonly program="$(basename "${0}")"
readonly applet="$(dirname "$(dirname "$(dirname "${0}")")")/MacOS/applet"
readonly app="$(dirname "$(dirname "$(dirname "${applet}")")")"

function syntax_error {
  echo "${program}: ${1}\nTry \`${program} --help\` for more information." >&2
  exit 1
}

function usage {
  echo "
    usage: ${program} [options]
    options:
      -m, --message <text>       Message text (mandatory).
      -t, --title <text>         Title text.
      -s, --subtitle <text>      Subtitle text.
      -a, --sound <sound_name>   Sound name (from /System/Library/Sounds)
      -h, --help                 Show this help.
  " | sed -E 's/^ {4}//'
}

while [[ "${1}" ]]; do
  case "${1}" in
    -h | --help)
      usage
      exit 0
      ;;
    -m | --message)
      NOTIFICATOR_MESSAGE="${2}"
      shift
      ;;
    -t | --title)
      NOTIFICATOR_TITLE="${2}"
      shift
      ;;
    -s | --subtitle)
      NOTIFICATOR_SUBTITLE="${2}"
      shift
      ;;
    -a | --sound)
      NOTIFICATOR_SOUND="${2}"
      shift
      ;;
    -*)
      syntax_error "unrecognized option: ${1}"
      ;;
    *)
      break
      ;;
  esac
  shift
done

if [[ -z "${NOTIFICATOR_MESSAGE}" ]]; then
  echo 'A message is mandatory.' >&2
  exit 1
fi

touch "${app}" # For some reason, if we do not do this the first time notifications will never fire
"${applet}"
