#!/bin/bash

readonly program="$(basename "${0}")"

usage() {
  echo "
    usage: ${program} <color> <files>

    Available color options:
      none (removes label), orange, red, yellow, blue, purple, green, gray
  " | sed -E 's/^ {4}//'
}

if [[ "${1}" =~ ^(-h|--help)$ ]]; then
  usage
  exit 0
fi

if [[ "${#}" -lt 2 ]]; then
  usage
  exit 1
fi

readonly color_name="${1}"
shift

# Check if color is valid and convert name to appropriate index
readonly color_array=('none' 'orange' 'red' 'yellow' 'blue' 'purple' 'green' 'gray')

for i in "${!color_array[@]}"; do
  [[ "${color_array[$i]}" == "${color_name}" ]] && color_index="${i}" && break
done

if [[ -z "${color_index}" ]]; then
  echo "Please pick a valid color."
  usage
  exit 1
fi

# Set the label
osascript - "${color_index}" "${@}" << EOF &>/dev/null
  on run argv
    set labelIndex to (item 1 of argv as number)
    repeat with i from 2 to (count of argv)
      tell application "Finder"
        set theFile to POSIX file (item i of argv) as alias
        set label index of theFile to labelIndex
      end tell
    end repeat
  end run
EOF
